// data/professors.js

const PROFESSORS = [
  // Deep Learning & Neural Networks
  {id:1,  name:"Yoshua Bengio",    title:"Full Professor",    uni:"Université de Montréal / Mila", country:"Canada",      field:"Machine Learning",      domain:"mila.quebec",        ssid:"1716854", research:"Deep learning, generative models, GFlowNets, AI safety, representation learning", papers:[{t:"Generative Flow Networks",y:2021,c:1240},{t:"Deep learning (textbook)",y:2015,c:58000}]},
  {id:2,  name:"Geoffrey Hinton",  title:"Emeritus Professor",uni:"University of Toronto",         country:"Canada",      field:"Deep Learning",         domain:"cs.toronto.edu",     ssid:"1813421", research:"Backpropagation, capsule networks, deep belief nets, Hopfield networks",         papers:[{t:"Reducing dimensionality of data with neural networks",y:2006,c:18900},{t:"ImageNet classification with deep CNNs",y:2012,c:75000}]},
  {id:3,  name:"Yann LeCun",       title:"Chief AI Scientist", uni:"NYU / Meta AI",                country:"USA",         field:"Deep Learning",         domain:"nyu.edu",            ssid:"1743128", research:"Convolutional neural networks, self-supervised learning, energy-based models, world models", papers:[{t:"Gradient-based learning applied to document recognition",y:1998,c:42000},{t:"A path towards autonomous machine intelligence",y:2022,c:1650}]},
  {id:4,  name:"Andrew Ng",        title:"Adjunct Professor",  uni:"Stanford University",           country:"USA",         field:"Machine Learning",      domain:"stanford.edu",       ssid:"1804833", research:"Deep learning, RL, AI for healthcare, MLOps, data-centric AI",                     papers:[{t:"Building high-level features using large scale unsupervised learning",y:2012,c:5600},{t:"Algorithms for inverse reinforcement learning",y:2000,c:4200}]},
  {id:5,  name:"Fei-Fei Li",       title:"Professor",          uni:"Stanford University",           country:"USA",         field:"Computer Vision",       domain:"stanford.edu",       ssid:"1982817", research:"Computer vision, ImageNet, AI for healthcare, human-centered AI, spatial intelligence", papers:[{t:"ImageNet: A large-scale hierarchical image database",y:2009,c:32000},{t:"Deep visual-semantic alignments for image captioning",y:2015,c:5400}]},
  {id:6,  name:"Kaiming He",       title:"Research Scientist", uni:"MIT",                           country:"USA",         field:"Computer Vision",       domain:"mit.edu",            ssid:"2133789", research:"ResNets, masked autoencoders, image recognition, feature pyramid networks",           papers:[{t:"Deep residual learning for image recognition",y:2016,c:102000},{t:"Masked autoencoders are scalable vision learners",y:2021,c:5600}]},
  {id:7,  name:"Ian Goodfellow",   title:"Research Scientist", uni:"Apple / Univ. of Montreal",     country:"USA",         field:"Generative AI",         domain:"apple.com",          ssid:"2300123", research:"GANs, adversarial examples, deep learning textbook, adversarial training",             papers:[{t:"Generative adversarial networks",y:2014,c:47000},{t:"Deep learning (textbook)",y:2016,c:41000}]},
  {id:8,  name:"Ilya Sutskever",   title:"Co-founder / CSO",   uni:"Safe Superintelligence (SSI)",  country:"USA",         field:"Deep Learning",         domain:"ssi.inc",            ssid:"2311234", research:"Sequence-to-sequence learning, transformers, GPT scaling, unsupervised multitask learning", papers:[{t:"Sequence to sequence learning with neural networks",y:2014,c:21000},{t:"Language models are unsupervised multitask learners",y:2019,c:18000}]},
  {id:9,  name:"Diederik Kingma",  title:"Research Scientist", uni:"Stanford / Google Brain",        country:"USA",         field:"Generative AI",         domain:"stanford.edu",       ssid:"2266890", research:"Variational autoencoders, normalising flows, diffusion models, GLOW",                  papers:[{t:"Auto-encoding variational Bayes (VAE)",y:2013,c:34000},{t:"Glow: Generative flow with invertible 1×1 convolutions",y:2018,c:3400}]},
  {id:10, name:"Bernhard Schölkopf",title:"Director",           uni:"MPI for Intelligent Systems",   country:"Germany",     field:"Machine Learning",      domain:"is.mpg.de",          ssid:"1726370", research:"Kernel methods, causal ML, causal representation learning, domain generalisation",     papers:[{t:"Toward Causal Representation Learning",y:2021,c:1100},{t:"A kernel two-sample test",y:2012,c:4200}]},

  // Machine Learning
  {id:11, name:"Michael Jordan",   title:"Professor",          uni:"UC Berkeley",                   country:"USA",         field:"Machine Learning",      domain:"berkeley.edu",       ssid:"1923789", research:"Statistical ML, graphical models, Bayesian nonparametrics, distributed optimisation", papers:[{t:"Graphical models, exponential families, and variational inference",y:2008,c:6700},{t:"An introduction to variational methods for graphical models",y:1999,c:5600}]},
  {id:12, name:"Percy Liang",      title:"Associate Professor",uni:"Stanford University",            country:"USA",         field:"Machine Learning",      domain:"stanford.edu",       ssid:"1967234", research:"Foundation models, HELM benchmark, data-centric AI, LLM evaluation, robustness",       papers:[{t:"On the opportunities and risks of foundation models",y:2021,c:7800},{t:"HellaSwag: Can a machine really finish your sentence?",y:2019,c:2100}]},
  {id:13, name:"Chelsea Finn",     title:"Assistant Professor",uni:"Stanford University",            country:"USA",         field:"Machine Learning",      domain:"stanford.edu",       ssid:"2178345", research:"Meta-learning, MAML, few-shot learning, robot learning from demonstrations",          papers:[{t:"Model-agnostic meta-learning for fast adaptation of deep networks",y:2017,c:11200},{t:"Learning to learn using gradient descent",y:2016,c:5400}]},
  {id:14, name:"Andreas Krause",   title:"Professor",          uni:"ETH Zurich",                     country:"Switzerland", field:"Machine Learning",      domain:"ethz.ch",            ssid:"2067345", research:"Bayesian optimisation, active learning, Gaussian processes, safe ML, submodular",      papers:[{t:"Information-theoretic regret bounds for Gaussian process optimisation",y:2012,c:3400},{t:"Safe exploration for RL",y:2017,c:1890}]},
  {id:15, name:"Neil Lawrence",    title:"Professor",          uni:"University of Cambridge",        country:"UK",          field:"Machine Learning",      domain:"cam.ac.uk",          ssid:"1934567", research:"Gaussian processes, AutoML, data science for developing nations, open data",            papers:[{t:"Gaussian process latent variable models",y:2005,c:4200},{t:"Data readiness levels",y:2017,c:890}]},
  {id:16, name:"Nando de Freitas", title:"Research Director",  uni:"Oxford / DeepMind",              country:"UK",          field:"Machine Learning",      domain:"ox.ac.uk",           ssid:"1823890", research:"Bayesian optimisation, RL, large language models, probabilistic ML",                   papers:[{t:"Taking the human out of the loop: Bayesian optimisation review",y:2016,c:7200},{t:"Grandmaster level in StarCraft II",y:2019,c:4500}]},
  {id:17, name:"Thomas Hofmann",   title:"Professor",          uni:"ETH Zurich",                     country:"Switzerland", field:"Machine Learning",      domain:"ethz.ch",            ssid:"1890123", research:"Scalable deep learning, distributed ML, NLP, recommendation systems",                  papers:[{t:"Probabilistic latent semantic indexing",y:1999,c:6700},{t:"Non-local neural networks",y:2018,c:6200}]},
  {id:18, name:"Sham Kakade",      title:"Professor",          uni:"Harvard University",              country:"USA",         field:"Machine Learning",      domain:"harvard.edu",        ssid:"1934890", research:"RL theory, online learning, spectral methods, statistical ML, PAC learning",            papers:[{t:"A natural policy gradient",y:2001,c:3800},{t:"Provably efficient RL with linear function approximation",y:2020,c:1500}]},

  // Data Science & Statistics
  {id:19, name:"David Blei",       title:"Professor",          uni:"Columbia University",            country:"USA",         field:"Data Science",          domain:"columbia.edu",       ssid:"1912678", research:"Probabilistic topic models, LDA, variational inference, Bayesian data analysis",      papers:[{t:"Latent Dirichlet Allocation",y:2003,c:37000},{t:"Variational inference: A review for statisticians",y:2017,c:5600}]},
  {id:20, name:"Ryan Tibshirani",  title:"Professor",          uni:"Carnegie Mellon University",     country:"USA",         field:"Data Science",          domain:"cmu.edu",            ssid:"1934890", research:"LASSO, high-dimensional statistics, conformal prediction, epidemiological forecasting",  papers:[{t:"Regression shrinkage and selection via the LASSO",y:1996,c:56000},{t:"Conformal prediction under covariate shift",y:2019,c:1230}]},
  {id:21, name:"Emmanuel Candès",  title:"Professor",          uni:"Stanford University",            country:"USA",         field:"Data Science",          domain:"stanford.edu",       ssid:"1956012", research:"Compressed sensing, conformal inference, knockoffs, matrix completion",                  papers:[{t:"Decoding by linear programming",y:2005,c:9800},{t:"Controlling the false discovery rate via knockoffs",y:2015,c:2300}]},
  {id:22, name:"Bin Yu",           title:"Professor",          uni:"UC Berkeley",                   country:"USA",         field:"Data Science",          domain:"berkeley.edu",       ssid:"1945901", research:"Reproducible data science, veridical data science, stability, deep learning theory",     papers:[{t:"Stability",y:2013,c:2300},{t:"Three principles of data science",y:2020,c:890}]},
  {id:23, name:"Susan Athey",      title:"Professor",          uni:"Stanford University",            country:"USA",         field:"Data Science",          domain:"stanford.edu",       ssid:"1901567", research:"Causal ML, heterogeneous treatment effects, platform economics, policy evaluation",       papers:[{t:"Generalized random forests",y:2019,c:3200},{t:"Machine learning methods economists should know",y:2019,c:4100}]},
  {id:24, name:"Stephan Günnemann",title:"Professor",          uni:"TU Munich",                      country:"Germany",     field:"Data Science",          domain:"tum.de",             ssid:"2045123", research:"Graph neural networks, robustness of ML, uncertainty quantification, spatio-temporal",    papers:[{t:"Deep Graph Infomax",y:2019,c:3400},{t:"Certifiable robustness for GNNs",y:2019,c:1230}]},

  // Natural Language Processing & LLMs
  {id:25, name:"Christopher Manning",title:"Professor",        uni:"Stanford University",            country:"USA",         field:"Natural Language Processing",domain:"stanford.edu",   ssid:"1738901", research:"NLP, dependency parsing, sentiment analysis, GloVe embeddings, BERT pre-training",     papers:[{t:"GloVe: Global vectors for word representation",y:2014,c:38000},{t:"The Stanford CoreNLP toolkit",y:2014,c:9800}]},
  {id:26, name:"Dan Jurafsky",      title:"Professor",          uni:"Stanford University",            country:"USA",         field:"Natural Language Processing",domain:"stanford.edu",   ssid:"1750234", research:"NLP, computational psycholinguistics, speech processing, dialogue systems, pragmatics", papers:[{t:"Speech and language processing (3rd ed.)",y:2023,c:15000},{t:"Discourse coherence in dialogue",y:2021,c:450}]},
  {id:27, name:"Graham Neubig",     title:"Associate Professor",uni:"Carnegie Mellon University",    country:"USA",         field:"Natural Language Processing",domain:"cmu.edu",         ssid:"2023456", research:"Low-resource NLP, multilingual models, code generation, machine translation",            papers:[{t:"A survey of cross-lingual word embedding models",y:2017,c:2300},{t:"CodeBERT: Pre-trained model for programming",y:2020,c:3100}]},
  {id:28, name:"Kyunghyun Cho",     title:"Associate Professor",uni:"New York University",           country:"USA",         field:"Natural Language Processing",domain:"nyu.edu",         ssid:"2322345", research:"Neural machine translation, GRU, seq2seq, multilingual AI, reasoning in LLMs",           papers:[{t:"Learning phrase representations using RNN encoder-decoder",y:2014,c:28000},{t:"On the properties of neural machine translation",y:2014,c:8900}]},
  {id:29, name:"Regina Barzilay",   title:"Professor",          uni:"MIT",                           country:"USA",         field:"Natural Language Processing",domain:"mit.edu",         ssid:"1789012", research:"NLP for medicine, AI for drug discovery, clinical text mining, antibiotic discovery",   papers:[{t:"Towards AI-driven drug discovery",y:2020,c:1230},{t:"A deep learning approach to antibiotic discovery",y:2020,c:2100}]},
  {id:30, name:"Pascale Fung",      title:"Professor",          uni:"HKUST",                          country:"Hong Kong",   field:"Natural Language Processing",domain:"ust.hk",          ssid:"2089123", research:"Empathetic AI, multilingual NLP, emotional intelligence in LLMs, human-robot dialogue", papers:[{t:"Towards empathetic open-domain conversation models",y:2019,c:1230},{t:"Empathetic dialogue generation",y:2020,c:980}]},
  {id:31, name:"Ji-Won Park",       title:"Associate Professor",uni:"Seoul National University",     country:"South Korea", field:"Natural Language Processing",domain:"snu.ac.kr",       ssid:"2112341", research:"Multilingual NLP, cross-lingual transfer, Korean language models, zero-shot learning",    papers:[{t:"Cross-lingual transfer learning for NLP",y:2022,c:567},{t:"Zero-shot multilingual summarisation",y:2023,c:312}]},

  // Reinforcement Learning
  {id:32, name:"Pieter Abbeel",     title:"Professor",          uni:"UC Berkeley",                   country:"USA",         field:"Reinforcement Learning", domain:"berkeley.edu",      ssid:"1720726", research:"Deep RL, robot learning, imitation learning, LLMs for robotics, foundation models",      papers:[{t:"Apprenticeship learning via inverse reinforcement learning",y:2004,c:3100},{t:"End-to-end training of deep visuomotor policies",y:2016,c:2800}]},
  {id:33, name:"Sergey Levine",     title:"Associate Professor",uni:"UC Berkeley",                   country:"USA",         field:"Reinforcement Learning", domain:"berkeley.edu",      ssid:"2012345", research:"Offline RL, robot learning, decision transformers, foundation models for robotics",      papers:[{t:"Offline RL as one big sequence modeling problem",y:2021,c:1890},{t:"Model-based RL for Atari",y:2019,c:1200}]},
  {id:34, name:"David Silver",      title:"Principal Researcher",uni:"UCL / DeepMind",              country:"UK",          field:"Reinforcement Learning", domain:"ucl.ac.uk",         ssid:"2189123", research:"AlphaGo, AlphaZero, MuZero, reward maximisation theory, self-play",                      papers:[{t:"Mastering the game of Go with deep neural networks",y:2016,c:14500},{t:"Mastering Atari, Go, chess and shogi by planning",y:2020,c:4500}]},
  {id:35, name:"Doina Precup",      title:"Research Scientist",  uni:"McGill / DeepMind",             country:"Canada",      field:"Reinforcement Learning", domain:"mcgill.ca",         ssid:"2200234", research:"Temporal abstraction, options framework, batch RL, healthcare RL, off-policy learning",   papers:[{t:"Between MDPs and semi-MDPs: The options framework",y:1999,c:3400},{t:"Off-policy temporal difference learning",y:2001,c:1890}]},
  {id:36, name:"Joelle Pineau",     title:"Professor",          uni:"McGill / Meta AI",              country:"Canada",      field:"Reinforcement Learning", domain:"mcgill.ca",         ssid:"2222456", research:"RL for healthcare, reproducibility in ML, POMDP, conversational AI policy",              papers:[{t:"Anytime point-based approximations for large POMDPs",y:2006,c:1890},{t:"Improving reproducibility in ML research",y:2021,c:890}]},
  {id:37, name:"Chelsea Finn",      title:"Assistant Professor",uni:"Stanford University",            country:"USA",         field:"Reinforcement Learning", domain:"stanford.edu",      ssid:"2178346", research:"Meta-RL, few-shot imitation learning, robot adaptation, offline meta-learning",           papers:[{t:"MAML: Model-agnostic meta-learning",y:2017,c:11200},{t:"Offline meta-reinforcement learning with advantage weighting",y:2021,c:450}]},
  {id:38, name:"Anca Dragan",       title:"Associate Professor",uni:"UC Berkeley",                   country:"USA",         field:"Reinforcement Learning", domain:"berkeley.edu",      ssid:"2189567", research:"Human-robot interaction, cooperative AI, inverse reward design, AI alignment, safety",    papers:[{t:"Cooperative inverse reinforcement learning",y:2016,c:1800},{t:"Legibility and predictability of robot motion",y:2013,c:2300}]},

  // Graph Neural Networks
  {id:39, name:"Michael Bronstein", title:"Professor",          uni:"University of Oxford",          country:"UK",          field:"Graph Neural Networks",  domain:"ox.ac.uk",          ssid:"2233567", research:"Geometric deep learning, GNNs, molecular GNNs, equivariant networks, protein structure",  papers:[{t:"Geometric deep learning: Going beyond Euclidean data",y:2017,c:5600},{t:"Graph neural networks: A review",y:2019,c:7800}]},
  {id:40, name:"Jure Leskovec",     title:"Professor",          uni:"Stanford University",           country:"USA",         field:"Graph Neural Networks",  domain:"stanford.edu",      ssid:"2244678", research:"Graph ML, knowledge graphs, drug discovery with GNNs, social network analysis",           papers:[{t:"node2vec: Scalable feature learning for networks",y:2016,c:9800},{t:"GCN for web-scale recommender systems",y:2018,c:3400}]},
  {id:41, name:"Xavier Bresson",    title:"Associate Professor",uni:"NTU Singapore",                 country:"Singapore",   field:"Graph Neural Networks",  domain:"ntu.edu.sg",        ssid:"2255789", research:"Graph transformers, combinatorial optimisation with GNNs, spectral graph theory",          papers:[{t:"Convolutional neural networks on graphs with spectral filtering",y:2016,c:7800},{t:"Residual gated graph convnets",y:2018,c:1230}]},

  // Generative AI & Diffusion Models
  {id:42, name:"Stefano Ermon",     title:"Associate Professor",uni:"Stanford University",            country:"USA",         field:"Generative AI",         domain:"stanford.edu",      ssid:"2277901", research:"Score-based generative models, diffusion models, ML for climate science",               papers:[{t:"Generative modeling by estimating gradients of data distribution",y:2019,c:5600},{t:"Score-based generative modeling through SDEs",y:2021,c:4500}]},
  {id:43, name:"Yang Song",         title:"Research Scientist", uni:"OpenAI / Stanford",             country:"USA",         field:"Generative AI",         domain:"stanford.edu",      ssid:"2288012", research:"Diffusion probabilistic models, score matching, latent diffusion, image generation",      papers:[{t:"Score-based generative modeling through stochastic DEs",y:2021,c:4500},{t:"Improved training of score-based models",y:2020,c:2300}]},
  {id:44, name:"Daphne Koller",     title:"Adjunct Professor",  uni:"Stanford / insitro",            country:"USA",         field:"Machine Learning",      domain:"stanford.edu",      ssid:"1794321", research:"Probabilistic graphical models, ML for drug discovery, generative biology",               papers:[{t:"Probabilistic Graphical Models (textbook)",y:2009,c:8900},{t:"SVM active learning with applications to text classification",y:2000,c:2100}]},

  // AI Safety & Alignment
  {id:45, name:"Stuart Russell",    title:"Professor",          uni:"UC Berkeley",                   country:"USA",         field:"AI Safety",             domain:"berkeley.edu",      ssid:"1867012", research:"AI safety, cooperative inverse RL, provably beneficial AI, value alignment, logic",       papers:[{t:"Artificial Intelligence: A Modern Approach (textbook)",y:2020,c:45000},{t:"Research priorities for robust and beneficial AI",y:2015,c:2300}]},
  {id:46, name:"Murray Shanahan",   title:"Professor",          uni:"Imperial College London",       country:"UK",          field:"AI Safety",             domain:"imperial.ac.uk",    ssid:"1834567", research:"LLM cognition, AI consciousness, embodied AI, talking about large language models",       papers:[{t:"Talking about large language models",y:2023,c:1200},{t:"The frame problem",y:2016,c:2300}]},
  {id:47, name:"Yang Liu",          title:"Professor",          uni:"Tsinghua University",            country:"China",       field:"AI Safety",             domain:"tsinghua.edu.cn",   ssid:"2155890", research:"Federated learning, trustworthy AI, privacy-preserving ML, fairness in ML",               papers:[{t:"Federated machine learning: Concept and applications",y:2019,c:5600},{t:"A survey of federated learning",y:2021,c:4500}]},
  {id:48, name:"Shafi Goldwasser",  title:"Professor",          uni:"MIT / Weizmann Institute",      country:"USA",         field:"AI Safety",             domain:"mit.edu",           ssid:"1867234", research:"Cryptography, zero-knowledge proofs, complexity theory, verifiable machine learning",      papers:[{t:"The knowledge complexity of interactive proof-systems",y:1989,c:7800},{t:"Probabilistic encryption",y:1984,c:5600}]},

  // Robotics & Engineering
  {id:49, name:"Angela Schoellig",  title:"Associate Professor",uni:"University of Toronto",         country:"Canada",      field:"Robotics",              domain:"utoronto.ca",       ssid:"2198765", research:"Aerial robotics, learning-based control, safe autonomy for drones",                     papers:[{t:"Safe learning in robotics",y:2021,c:578},{t:"Real-time trajectory generation for quadrotors",y:2012,c:3400}]},
  {id:50, name:"Hans Bauer",        title:"Professor",          uni:"TU Munich",                      country:"Germany",     field:"Robotics",              domain:"tum.de",            ssid:"2201567", research:"Autonomous vehicles, computer vision, sensor fusion, LiDAR-camera fusion for mobility",   papers:[{t:"Multi-sensor fusion for autonomous driving perception",y:2022,c:567},{t:"LiDAR-camera fusion for 3D object detection",y:2021,c:489}]},
  {id:51, name:"Sarah Lindqvist",   title:"Professor",          uni:"KTH Royal Institute",           country:"Sweden",      field:"Engineering",           domain:"kth.se",            ssid:"2088431", research:"Renewable energy data analytics, wind turbine optimisation, smart grid integration",      papers:[{t:"Optimal control of wind farm power output using ML",y:2022,c:287},{t:"Smart grid frequency regulation with variable generation",y:2021,c:312}]},
  {id:52, name:"Mark de Vries",     title:"Associate Professor",uni:"TU Delft",                      country:"Netherlands", field:"Robotics",              domain:"tudelft.nl",        ssid:"2076543", research:"Autonomous systems, robot perception, human-robot collaboration in manufacturing",        papers:[{t:"Human-robot collaboration in unstructured environments",y:2023,c:198},{t:"Vision-based grasping for industrial robots",y:2022,c:156}]},

  // Medicine & Biology
  {id:53, name:"Karl Deisseroth",   title:"Professor",          uni:"Stanford University",            country:"USA",         field:"Neuroscience",          domain:"stanford.edu",      ssid:"2109874", research:"Optogenetics, CLARITY brain mapping, neural circuit analysis, psychiatric disorders",    papers:[{t:"Millisecond-timescale optical control of neural activity",y:2005,c:8900},{t:"CLARITY for mapping the nervous system",y:2013,c:6700}]},
  {id:54, name:"David Baker",       title:"Professor",          uni:"University of Washington",      country:"USA",         field:"Biology",               domain:"uw.edu",            ssid:"2001234", research:"Protein design, computational biology, de novo protein folding, RoseTTAFold",            papers:[{t:"Accurate prediction of protein structures using RoseTTAFold",y:2021,c:3200},{t:"Design of a novel globular protein fold",y:2003,c:4100}]},
  {id:55, name:"Sarah Gilbert",     title:"Professor",          uni:"University of Oxford",          country:"UK",          field:"Medicine",              domain:"ox.ac.uk",          ssid:"2190234", research:"Vaccine development, viral vector vaccines, ChAdOx platform, pandemic preparedness",      papers:[{t:"Safety and efficacy of the ChAdOx1 nCoV-19 vaccine",y:2021,c:12000},{t:"Correlates of protection against COVID-19",y:2022,c:3400}]},
  {id:56, name:"Ananya Krishnan",   title:"Associate Professor",uni:"National University of Singapore",country:"Singapore", field:"Biology",               domain:"nus.edu.sg",        ssid:"2198234", research:"Stem cell biology, regenerative medicine, organoid technology, organ-on-chip systems",    papers:[{t:"Human intestinal organoids as a model for enteric infections",y:2022,c:456},{t:"Directed differentiation of pluripotent stem cells",y:2021,c:678}]},

  // Economics & Business
  {id:57, name:"Esther Duflo",      title:"Professor",          uni:"MIT",                           country:"USA",         field:"Economics",             domain:"mit.edu",           ssid:"1978234", research:"Development economics, randomised control trials, poverty reduction, education access",   papers:[{t:"The experimental approach to development economics",y:2009,c:8900},{t:"Women as policy makers: A randomized experiment",y:2004,c:5600}]},
  {id:58, name:"Daron Acemoglu",    title:"Professor",          uni:"MIT",                           country:"USA",         field:"Economics",             domain:"mit.edu",           ssid:"1890456", research:"Institutional economics, political economy, AI and labour market inequality",              papers:[{t:"Why nations fail",y:2012,c:12000},{t:"Robots and jobs: Evidence from US labor markets",y:2020,c:4500}]},
  {id:59, name:"Amelia Thornton",   title:"Professor",          uni:"University of Melbourne",       country:"Australia",   field:"Business",              domain:"unimelb.edu.au",    ssid:"2223456", research:"Behavioural economics, consumer decision-making, financial wellbeing policy",              papers:[{t:"Present bias and financial decision-making",y:2022,c:312},{t:"Nudge interventions for retirement savings",y:2021,c:456}]},

  // Physics & Materials Science
  {id:60, name:"Michelle Simmons",  title:"Professor",          uni:"University of New South Wales", country:"Australia",   field:"Physics",               domain:"unsw.edu.au",       ssid:"2134678", research:"Quantum computing with silicon qubits, atomic-scale fabrication, quantum error correction",papers:[{t:"Atomic-scale silicon device with controllable single-electron transport",y:2009,c:2300},{t:"A single-atom transistor",y:2012,c:3100}]},
  {id:61, name:"Immanuel Bloch",    title:"Professor",          uni:"LMU Munich",                    country:"Germany",     field:"Physics",               domain:"lmu.de",            ssid:"2156890", research:"Ultracold atoms, optical lattices, quantum many-body physics, quantum simulation",        papers:[{t:"Quantum phase transition from a superfluid to a Mott insulator",y:2002,c:9800},{t:"Many-body physics with ultracold gases",y:2008,c:8900}]},
  {id:62, name:"Anne L'Huillier",   title:"Professor",          uni:"Lund University",               country:"Sweden",      field:"Physics",               domain:"lu.se",             ssid:"2167901", research:"Attosecond physics, ultrafast lasers, high harmonic generation, electron dynamics",       papers:[{t:"High-order harmonic generation in rare gases",y:1993,c:4500},{t:"Attosecond measurement of electron dynamics in atoms",y:2001,c:3200}]},

  // Mathematics
  {id:63, name:"Terrence Tao",      title:"Professor",          uni:"UCLA",                          country:"USA",         field:"Mathematics",           domain:"ucla.edu",          ssid:"1889123", research:"Harmonic analysis, number theory, partial differential equations, compressed sensing",    papers:[{t:"Decoding by linear programming",y:2005,c:9800},{t:"The prime k-tuples conjecture",y:2012,c:1230}]},
  {id:64, name:"Ingrid Daubechies", title:"Professor",          uni:"Duke University",               country:"USA",         field:"Mathematics",           domain:"duke.edu",          ssid:"1878012", research:"Wavelets, signal processing, mathematical imaging, deep learning theory foundations",    papers:[{t:"Ten lectures on wavelets",y:1992,c:24000},{t:"Iteratively reweighted least squares",y:2010,c:2300}]},
  {id:65, name:"Manjul Bhargava",   title:"Professor",          uni:"Princeton University",          country:"USA",         field:"Mathematics",           domain:"princeton.edu",     ssid:"2133678", research:"Number theory, representation of quadratic forms, arithmetic geometry, Bhargava cube",   papers:[{t:"Higher composition laws and applications",y:2004,c:1230},{t:"The density of discriminants of quartic fields",y:2005,c:890}]}
];

function searchProfessors({ q = '', field = '', country = '', limit = 60, offset = 0 }) {
  const query = q.toLowerCase().trim();
  let results = PROFESSORS;

  if (query) {
    results = results.filter(p =>
      p.name.toLowerCase().includes(query) ||
      p.uni.toLowerCase().includes(query) ||
      p.research.toLowerCase().includes(query) ||
      p.field.toLowerCase().includes(query) ||
      p.country.toLowerCase().includes(query) ||
      p.papers.some(pp => pp.t.toLowerCase().includes(query))
    );
  }
  if (field)   results = results.filter(p => p.field.toLowerCase().includes(field.toLowerCase()));
  if (country) results = results.filter(p => p.country === country);

  const total = results.length;
  return { data: results.slice(offset, offset + Math.min(limit, 100)), total };
}

function getFields()     { return [...new Set(PROFESSORS.map(p => p.field))].sort(); }
function getCountries()  { return [...new Set(PROFESSORS.map(p => p.country))].sort(); }

module.exports = { PROFESSORS, searchProfessors, getFields, getCountries };
